Add files via upload
lil-il/betting_shop pull request #11
Opened 2021-05-09 09:26 UTC by Andrlluuk

Либо оставляем такую реализацию, либо можно попробовать добавить нормальный DbContext с миграциями entity framework и тд. Тогда сразу поправлю, если нужно

2021-05-11 13:14 UTC, Gordory commented on DB/IEventRepository.cs
> +    public class ExistingEvent
Это что за класс? 
Я так понимаю из мастера? Но зачем скопировал?

2021-05-11 13:14 UTC, Gordory commented on DB/IEventRepository.cs
> +        ExistingEvent GetExistingEventByID(int EventId);
Чтобы было единообразно - Id, с маленькой d

2021-05-11 13:14 UTC, Gordory commented on DB/IEventRepository.cs
> +        bool Save();
Что это за метод? Зачем он нужен?

2021-05-11 13:14 UTC, Gordory commented on DB/IEventRepository.cs
> +        void DeleteEvent(int Id);
Тут везде Create _Event_, Update _Event_, а в названии уже есть _Event_ Repository, давай из методов уберем эти слова ExistingEvent

2021-05-11 13:14 UTC, Gordory commented on DB/EventRepository.cs
> +        public void DeleteEvent(int studentID)
Кто такой student?

2021-05-11 13:14 UTC, Gordory commented on DB/EventRepository.cs
> +        public void DeleteEvent(int studentID)
Если копируешь - вычитывай код который отправляешь в коммит

2021-05-11 13:14 UTC, Gordory commented on DB/DBSQLite.cs
> +namespace WebApplication1.DB
Почему отдельный проект в солюшне не создал? 
И с названием неймспейсов что-то явно не так

2021-05-11 13:14 UTC, Gordory commented on DB/DBSQLite.cs
> +           @"C:\Users\andrl\source\repos\WebApplication1\WebApplication1\Tables\events.db;";
Это будет работать только у тебя на компьютере?
Как сделать так чтобы работало везде?

2021-05-11 13:14 UTC, Gordory commented on DB/DBSQLite.cs
> +            using (SQLiteConnection Connect = new SQLiteConnection("Data Source=C:\\Users\\andrl\\source\\repos\\WebApplication1\\WebApplication1\\Tables\\events.db;"))
А зачем тут опять явно указан путь до файла? Он же уже вынесен в константы?

2021-05-11 15:27 UTC, Andrlluuk commented on DB/IEventRepository.cs
> +        void DeleteEvent(int Id);
всмысле название переменной?

2021-05-13 10:12 UTC, Gordory commented on DB/IEventRepository.cs
> +        void DeleteEvent(int Id);
Название метода, да

2021-05-15 06:25 UTC, Andrlluuk commented on DB/IEventRepository.cs
> +    public class ExistingEvent
а как мне его лучше добавить, чтобы у меня все компилилось, но пока без ксюшиного класса? Можно завести интерфейс этой штуки, а можно все-таки от ксюшиного проекта сделать солюшн и сразу зависимости прописать.
Просто чет хз как это норм сделать

2021-05-15 06:48 UTC, Andrlluuk commented on DB/IEventRepository.cs
> +        void DeleteEvent(int Id);
Не понял(  у ксюши же называется класс ивента: ExistingEvent. Получается я могу только название передаваемого в метод ExistingEvent'а поменять на Event

2021-05-15 07:02 UTC, Gordory commented on DB/IEventRepository.cs
> +    public class ExistingEvent
Не понимаю зачем без ксюшиного класса это делать. 
Ну вообще хорошо бы чтобы вы были в одном солюшне все. Сейчас проблема в том что все они разные. Пока можно создать проект внутри солюшна Ксюши и там зависимость от её проекта поставить

2021-05-15 07:03 UTC, Gordory commented on DB/IEventRepository.cs
> +        void DeleteEvent(int Id);
Стоп.У тебя просто слово Event дублируется. Убери его из **названий методов** и всё.

2021-05-15 07:04 UTC, Gordory commented on DB/IEventRepository.cs
> +        void DeleteEvent(int Id);
Пусть будут просто Create, Update, Delete, GetAll

2021-05-15 07:05 UTC, Gordory commented on DB/IEventRepository.cs
> +    public class ExistingEvent
А потом когда все перенесете в один - просто почистишь код

2021-05-16 06:10 UTC, Gordory requested changes

2021-05-16 06:10 UTC, Gordory commented on betting-shop.DataBase/Program.cs
>      public class Program
Не очень понимаю зачем тебе тут Webapplication вообще. Давай превратим этот проект в библиотеку классов? Уберем стартап, мейн, jaon файлы и оставим только важные классы.

чтобы их протестировать сделай отдельный проект с тестами своего репозитория
betting-shop.database.tests

2021-05-26 11:00 UTC, Gordory requested changes

2021-05-26 11:00 UTC, Gordory commented on BettingShop.sln
> +EndProject
Проекты давай переименуем как у остальных
`BettingShop.Database` и `BettingShop.Database.Tests`
и папочки тоже

2021-05-26 11:00 UTC, Gordory commented on betting_shop.database.tests/UnitTest1.cs
> +    public class UnitTest1
Название класса. Наверное это `EventRepositoryTests`?

2021-05-26 11:00 UTC, Gordory commented on betting_shop.database/DB/Deserializer.cs
> +    static class Deserializer
Зачем `static`?

И `public` забыл

2021-05-26 11:00 UTC, Gordory commented on betting_shop.database/DB/EventRepository.cs
> +        }
Зачем эти методы доступны пользователю класса?

2021-05-26 11:00 UTC, Gordory commented on betting_shop.database/betting_shop.database.csproj
> +  </ItemGroup>
Что это за projectreference? его же уже давно не существует

2021-05-27 09:33 UTC, Gordory requested changes

2021-05-27 09:33 UTC, Gordory commented on BettingShop.DataBase/DB/Deserializer.cs
> +    public class Deserializer
Ну тут ты убрал static, а методы то остались статиком.

Давай весь класс сделаем не статик и будем в конструктор репозитория прокидывать

2021-05-27 11:58 UTC, Andrlluuk commented on BettingShop.DataBase/DB/Deserializer.cs
> +    public class Deserializer
есть смысл интерфейс делать или можно прям явно тип в репо написать?

2021-05-28 09:00 UTC, Gordory commented on BettingShop.DataBase/DB/Deserializer.cs
> +    public class Deserializer
Интерфейс всегда есть смысл делать, потому что мокать класс ты не сможешь и это повлияет на тестируемость. Но в целом пока можно и без него

2021-05-28 09:01 UTC, Gordory approved these changes

2021-05-28 10:05 UTC, Gordory requested changes

2021-05-28 10:05 UTC, Gordory commented on BettingShop.DataBase/DB/IEventRepository.cs
> +        Task<BetEvent.Api.Models.BetEvent> Delete(Guid Id);
По договорённости между разработчиками у всех асинхронных методов должны быть `Async` суффиксы на конце. `CreateAsync`, `DeleteAsync` и т.д.

2021-05-28 11:57 UTC, Gordory approved these changes

2021-05-29 03:56 UTC, merged