Bot develop
lil-il/betting_shop pull request #12
Opened 2021-05-12 12:38 UTC by lil-il

2021-05-14 10:14 UTC, Gordory requested changes

2021-05-14 10:14 UTC, Gordory commented on EchoBotForTest/EchoBotForTest/AliasAttribute.cs
> +namespace EchoBotForTest
Пора переименовать уже namespace и название проекта

2021-05-14 10:14 UTC, Gordory commented on EchoBotForTest/EchoBotForTest/AliasAttribute.cs
> +namespace EchoBotForTest
Кажется нужно положить бота в отдельный проект в корневой солюшн

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/AliasAttribute.cs
> +namespace EchoBotForTest
namespace надо поменять во всём проекте, чтобы соответствовало названию проекта в солюшне

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/AliasAttribute.cs
> +namespace EchoBotForTest
Предлагаю переименовать проект еще раз в BettingShop.Telegram.Bot, тогда namespace соответствующий будет и будет легче потом конфликты namespace решать потенциальные

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Command/Commands/CreateEventCommandState.cs
> +        }
Наверное правильнее будет убрать `set;` у свойства, чтобы это свойство только через конструктор проставлялось. Такой immutable класс получится

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Command/Commands/NoCommandCommandState.cs
> +    }
А раз у этой команды нет состояния - зачем `State` для неё?

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Command/Commands/CreateEventCommandState.cs
> +        }
Либо второй вариант - убрать конструктор и свойство только через сеттер задавать.
Надо выбрать и у всех стейтов поправить

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Command/Commands/PlaceBetCommandType.cs
> +        public string Name => "CreateEvent";
Имя видимо неправильное тут

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Config.cs
> +        public static string Token = "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ";
Такое лучше не коммитить в репозиторий. Этот реп - публичный, любой теперь может воспользоваться твоим ключом для неприятных штук.

Есть два варианта как хранить. При запуске программы считывать либо из файла, который никогда не коммитится, либо передавать в параметрах запуска каждый раз при запуске программы. Подумай как удобнее будет и лучше перевыпустить токен, если это возможно, а этот отсюда убрать.

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +        public async Task ExecuteAsync(Telegram.Bot.Types.Message message, TelegramBotClient client, ICommandState<CreateEventCommandType> state)
Хм, а клиента может лучше из конструктора прокидывать при создании класса, а не каждый раз пихать в метод?

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +            throw new NotImplementedException();
Можно просто сделать ECHO, чтобы пользователю отвечалось какой executor был вызван и с какими параметрами и стейтом, для тестов

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +            throw new NotImplementedException();
Ну и, соответственно, во всех экзекьютерах пока так сделать

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Executor/Executors/GetMyIdExecutor.cs
> +    public class GetMyIdExecutor: IExecutor
А `IExecutor` же дженерик?
Зачем вообще нужна такая опция для пользователя?

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Executor/Executors/NoCommandExecutor.cs
> +        public async Task ExecuteAsync(Telegram.Bot.Types.Message message, TelegramBotClient client, ICommandState<NoCommandType> state)
Чет сижу и прям вижу что не очень удобно, что для всех команд надо иметь state. Некоторые могут быть вполне себе stateless же. 
Давай вместе подумаем как это перепроектировать

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Executor/Executors/NoCommandExecutor.cs
> +        public async Task ExecuteAsync(Telegram.Bot.Types.Message message, TelegramBotClient client, ICommandState<NoCommandType> state)
Либо забить пока, сделать все команды stateful, даже если реально стейта нет, а править потом если будет время

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/MessageHandling/ICommandSerializer.cs
> +    }
Это наверное всё-таки `ICommandTypeParser` и метод `Parse`

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/Program.cs
> +            telegramHandler.StopReceiving();
Это не очень хорошее решение. Как сделать красиво? Использовать `CancellationToken`
Пример накидал: https://pastebin.com/eY5gMTng

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/TelegramBot.csproj
> +    <PackageReference Include="Ninject" Version="3.3.4" />
Я советую юзать для начала `LightInject`, просто потому что сам его использую, мне легче будет подсказать

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/User/IUser.cs
> +        public long Id { get; set; }
При добавлении новой команды со стейтом - в этом классе будут появляться свойства. Это нарушение Open-closed principle. Надо вынести привязку стейта к пользователям в какой-нибудь отдельный класс, который будет хранить в себе стейты для каждого пользователя

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/User/IUser.cs
> +    public interface IUser
Я бы всё-таки назвал `ITelegramUser`

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +            userRequest.User = user;
Не понял. А откуда `user` справа берётся?

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +                    var executor = executorsManager.GetExecutorFromState(user.State);
Ну вместо этого класса лучше наверное использовать поиск нужного типа через Reflection.
Сделать какой-нибудь класс-фабрику `ExecutorFactory` с методом `GetExecutor(ICommandType commandType)` и туда прокинуть контейнер, из которого дергать нужные типы при запросе.

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +                    var state = stateManager.GetStateFromString(user.State);
А вот с этим классом можно так поступить - если убрать из пользователя стейты - то можно сделать класс который будет внутри себя хранить пары `ITelegramUser, ICommandState`. Чтобы так сделать, надо выделить не дженерик интерфейс `ICommandState` и отнаследоваться `ICommandState<T> : ICommandState`, например так

2021-05-14 10:14 UTC, Gordory commented on TelegramBot/User/TelegramUser.cs
> +        }
С идентификатором проблема - надо выбрать, либо прокидывать через конструктор, либо сеттером. Первый вариант - immutable style, и кажется что он максимально правильный в этом случае

2021-05-14 10:52 UTC, lil-il commented on TelegramBot/Command/Commands/NoCommandCommandState.cs
> +    }
Чтобы в екзекьютор передавать что-то. Я просто чёт не понял как это нормально по-другому сделать

2021-05-14 10:56 UTC, lil-il commented on TelegramBot/Executor/Executors/NoCommandExecutor.cs
> +        public async Task ExecuteAsync(Telegram.Bot.Types.Message message, TelegramBotClient client, ICommandState<NoCommandType> state)
Давай пока сделаем stateful, а потом посмотрим, я это обсуждение не буду пока просто закрывать

2021-05-14 11:05 UTC, Gordory requested changes

2021-05-14 11:05 UTC, Gordory commented on TelegramBot/Program.cs
> +                botClient,
Тут надо у `BotHandler` сделать чтобы он интерфейс принимал, а не класс.

2021-05-14 11:05 UTC, Gordory commented on TelegramBot/Program.cs
> +            telegramHandler.StopReceiving();
Так, я почитал и разобрался во всей этой истории. Проблема в том, что телеграм сделал у себя клиента именно так, с идеей `fire and forget`.

Идеальный вариант - написать свой метод, который хендлит апдейты. Вот я накидал пример: https://pastebin.com/h47TJJmX 

Чтобы осталась работа с `Initialize` и появился CancellationToken - можно добавить к коду из прошлого комментария так:
```
while (!token.IsCancellationRequested)
{
  await Task.Delay(TimeSpan.FromSeconds(60), token); 
{
```

2021-05-14 11:24 UTC, lil-il commented on TelegramBot/Config.cs
> +        public static string Token = "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ";
норм просто конфиг в гитигнор добавить?

2021-05-14 11:40 UTC, lil-il commented on TelegramBot/User/IUser.cs
> +        public long Id { get; set; }
То есть класс, который хранит Юзера и все стейты? А как из него вытаскивать стэйты для конкретного юзера?

2021-05-14 11:42 UTC, lil-il commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +            throw new NotImplementedException();
прям в консоль это печатать? или как?

2021-05-14 12:00 UTC, Gordory commented on TelegramBot/Config.cs
> +        public static string Token = "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ";
Нет, тогда проект же собираться перестанет. Плюс гитигнор влияет на файлы, которые только добавляются в коммит. А этот файл ты уже закоммитил

2021-05-14 12:03 UTC, Gordory commented on TelegramBot/Config.cs
> +        public static string Token = "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ";
Можно сделать просто. Положить где-то json файл с конфигом и добавить его в гитигнор, не делая коммит. А в мейне при запуске читать этот файл и через `JSONConvert.Deserialize` создавать этот класс и класть в конструктор

2021-05-14 12:04 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +            throw new NotImplementedException();
Нет, отвечать юзеру обратно сообщение. Там же есть у клиента телеграма отправка сообщений

2021-05-14 12:04 UTC, Gordory commented on TelegramBot/Executor/Executors/NoCommandExecutor.cs
> +        public async Task ExecuteAsync(Telegram.Bot.Types.Message message, TelegramBotClient client, ICommandState<NoCommandType> state)
Договорились

2021-05-14 12:06 UTC, Gordory commented on TelegramBot/User/IUser.cs
> +        public long Id { get; set; }
Ну сделать публичный метод `GetState(IUser user)` который будет вытаскивать для пользователя его актуальный стейт. Для одного юзера он всегда один

2021-05-14 12:06 UTC, Gordory commented on TelegramBot/User/IUser.cs
> +        public long Id { get; set; }
Класс будет хранить все пары юзер-его стейт

2021-05-14 12:08 UTC, Gordory commented on TelegramBot/User/IUser.cs
> +        public long Id { get; set; }
https://github.com/lil-il/betting_shop/pull/12#discussion_r632428503

2021-05-14 12:14 UTC, Gordory requested changes

2021-05-14 12:14 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +        private ICommandTypeParser _typeParser;
Все что не изменяется в классе стоит делать readonly, например зависимости которые из конструктора прилетают

2021-05-14 12:14 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +        private ICommandTypeParser _typeParser;
И во всех классах тоже пробегись проверь

2021-05-14 12:14 UTC, Gordory commented on TelegramBot/Executor/Executors/NoCommandExecutor.cs
> +        public NoCommandExecutor(ITelegramBotClient botClient)
По кодстайлу конструкторы сразу после приватных полей, но перед методами класса. И во всех классах так стоит глянуть

2021-05-15 06:29 UTC, lil-il commented on TelegramBot/BotHandler.cs
> +                    var state = stateManager.GetStateFromString(user.State);
А почему нельзя просто хранить пары ITelegramUser, ICommandState<ICommandType>?

2021-05-15 06:57 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +                    var state = stateManager.GetStateFromString(user.State);
Не понял вопроса. Потому что сейчас комманд стейт дженерик

2021-05-15 06:58 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +                    var state = stateManager.GetStateFromString(user.State);
Ну мы в общем-то и так просто будем эти пары хранить

2021-05-15 07:14 UTC, lil-il commented on TelegramBot/Config.cs
> +        public static string Token = "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ";
Как его прописать в гитигноре, чтобы он не добавлялся? Я вроде его туда вношу, а он все равно добавляется. После того как получится нормально это сделать, поменяю токен.

2021-05-15 07:15 UTC, lil-il commented on TelegramBot/BotHandler.cs
> +                    var state = stateManager.GetStateFromString(user.State);
ой, я имел в виду ITelegramUser, IcommandState<IcommandType>

2021-05-17 05:01 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +                    var state = stateManager.GetStateFromString(user.State);
Мне сложно объяснить но короче будет проблема что в марте вызова метода get тебе надо будет знать дженерик тип, а это рушит все обобщение. ну а если пытаться дженерик от интерфейса сделать то так нельзя, воткнешься в органичения C#

в целом ты можешь попробовать и быстро увидишь почему не сработает. а потом легко поправишь

2021-05-17 05:04 UTC, Gordory requested changes

2021-05-17 05:04 UTC, Gordory commented on TelegramBot/Config.json
> +  "Token": "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ"
Тебе не надо было этот файл коммитить. надо было чтобы он существовал у тебя только локально,либо как заглушка. я например делаю как. создаю файл с заглушкой, коммичу, добавляю в gitignore и потом локально заглушку меняю на нужный токен перед запусками

2021-05-19 17:19 UTC, lil-il commented on TelegramBot/MessageHandling/UserMessageParser.cs
> +                if (splitedMessage[i] == "Createevent") //какой-то из команд
тут надо как-то с нашим Alias-ом работать. Но как?

2021-05-19 17:19 UTC, lil-il commented on TelegramBot/ExecutorsFactory.cs
> +                .Select(T => container.GetInstance(T)).Cast<IExecutor>().First();
Не работает "Sequence contains no elements"

2021-05-19 17:19 UTC, lil-il commented on TelegramBot/MessageHandling/UserMessageParser.cs
> +                }
Надо как-то с AliasAttribute работать, наверное. Пока не разобрался как

2021-05-19 17:24 UTC, Gordory commented on TelegramBot/MessageHandling/UserMessageParser.cs
> +                }
Ну так же через Reflection

2021-05-20 05:25 UTC, Gordory commented on TelegramBot/ExecutorsFactory.cs
> +                .Select(T => container.GetInstance(T)).Cast<IExecutor>().First();
Попробуй ` T.BaseType.IsAssignableFrom(typeof(IExecutor))` тут поменять местами типы

2021-05-20 08:38 UTC, Gordory commented on TelegramBot/MessageHandling/UserMessageParser.cs
> +                if (splitedMessage[i] == "Createevent") //какой-то из команд
В треде ниже отписал

2021-05-24 10:04 UTC, Gordory requested changes

2021-05-24 10:04 UTC, Gordory commented on BettingShop.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "BettingShop.TelegramBot", "TelegramBot\BettingShop.TelegramBot.csproj", "{D35C5DBF-9F77-4669-A3FA-7FE9DCD131C3}"
Го переименуем `TelegramBot` папочку в `BettingShop.TelegramBot` чтобы соответствовало. И в gitignore тоже

2021-05-24 10:04 UTC, Gordory commented on .gitignore
> +.TelegramBot/Config.json/
Предлагаю добавить подпапочку `configs`. Чтобы стало `TelegramBot/configs/Config.json`

Кстати, ошибка почему не игнорится в том, что у тебя зачем-то точка стоит перед `TelegramBot`, а такой папки не существует

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/BettingShop.TelegramBot.csproj
> +  </ItemGroup>
А это зачем?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Config.json
> +  "Token": "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ"
Так, давай сделаем так. Вот этот файл я предлагаю поменять, мы примем изменения, а **локально** при запуске будем прописывать нужный токен, а файл попадёт в gitignore

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Config.json
> +  "Token": "1669291330:AAHZ-qdBkVbGS7TaOJm85XLyDMxqG3C65bQ"
```suggestion
  "Token": "SomeTelegramBotPrivateToken"
```

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +                        break;
Кажется что в этой ветке кода у нас ещё не будет названия. Давай введём `CreateEventState.Start`?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +                        //сохранить название события
Еще мне кажется "сохранить название события" уже можно прям в сам `state`. Давай туда добавим ссылку на класс, который будет "формирующимся" событием и будем эту ссылку на каждом этапе менять на дополненное новой инфой событие?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +                        //сохранить название события
В данный момент ты уже можешь пользоваться клиентом, который смержила Ксюша, для этого тебе надо поребейзиться на мастер. Что такое rebase я кидал где почитать в чат :)

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/GetMyIdExecutor.cs
> +    public class GetMyIdExecutor: IExecutor
Давай пока просто снесём нафиг этот класс? Потребуется - добавим

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/PlaceBetExecutor.cs
> +                        if (true) //если введен существующий номер
Я думаю эту проверку будет Api на своей стороне делать. Ты просто будешь делать запрос "поставь ставку", а если Api ответит, например, 404 - обработаешь это и выведешь другое сообщение.

Пока оставим так, потому что клиента ты еще не использовал

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/ProfileInfoExecutor.cs
> +    class ProfileInfoExecutor : IExecutor<ProfileInfoCommandType>
`public`?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/ProfileInfoExecutor.cs
> +    class ProfileInfoExecutor : IExecutor<ProfileInfoCommandType>
И везде где забыл

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +        private static Dictionary<ITelegramUser, ICommandState> userState = new Dictionary<ITelegramUser, ICommandState>();
Зачем `static`?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +        private static Dictionary<ITelegramUser, ICommandState> userState = new Dictionary<ITelegramUser, ICommandState>();
В многопоточной среде развалится, `Dictionary` не потокобезопасный, лучше использовать `ConcurrentDictionary`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +            var currentType = userState[user].GetType().GetInterface("ICommandState`1").GetGenericArguments().First();
Не-не-не, никаких строковых констант. Переименует кто-то другой этот интерфейс и всё, всё развалится, потому что про это место он не знал.

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +    public class UserService : IUserCommandStateService, IUserCommandTypeService
Давай интерфейсы и класс в отдельные файлы разнесём.
И еще `UserService` это слишком общее название, давай сделаем `UserCommandStateService`?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +        private ServiceContainer container;
Кажется пора отсюда выпилить `ServiceContainer`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +            var statetype = userState[user].GetType();
`stateType` нигде не используется

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +            var currentType = userState[user].GetType().GetInterface("ICommandState`1").GetGenericArguments().First();
Тебе поможет метод с названием `GetGenericTypeDefinition`, он позволяет из сконструированного дженерик-типа вытащить определение универсального типа, то есть из `ICommandState<CreateEventCommandType>` этот метод вытащит `ICommandState<>`

https://docs.microsoft.com/ru-ru/dotnet/api/system.type.getgenerictypedefinition?view=net-5.0

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/MessageHandling/CommandParser.cs
> +            //return new UnknownCommandType();
Если код ниже работает - надо снести комментарии, этот код всё равно в гите останется старый

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/MessageHandling/UserMessage.cs
> +        public Telegram.Bot.Types.Message telegramMessage { get; set; }
С большой буквы `TelegramMessage`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Program.cs
> +            var r = new StreamReader("C:/Users/iprok/bot/betting_shop/TelegramBot/Config.json");
Сделай `Config.json` ресурсом и выстави у него `CopyAlways`, тогда он всегда будет попадать в выходную директорию, я об этом в чате писал. И тогда можно будет относительный путь наладить

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Program.cs
> +        private static CommandParser commandParser;
Убери статик поля, используй лучше просто локальные переменные

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Program.cs
> +                commandParser);
Давай всё это вынесем в отдельные методы? 

`ServiceContainer CreateContainer()`

и

`void RegisterDependencies(ServiceContainer container)`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Program.cs
> +                commandParser);
Тогда код будет выглядеть так:

```
var container = CreateContainer();
RegisterDependencies(container);
var telegramHandler = container.GetInstance<BotHandler>();
telegramHandler.Initialize();

...
```

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +            var userRequest = parser.ParseMessage(e.Message.Text);
Надо бы посмотреть по хорошему как работают боты с кнопочками, но пока лучше добить функционал MVP, а потом этим заняться

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +            client = botClient;
`this.`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/HelpExecutor.cs
> +                $" - /profileinfo - посмотреть информацию о профиле");
Потенциально можно добавить помимо `Alias` атрибут `Description` и тут собирать всю информацию по всем типам команд с помощью `Reflection`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/Executors/PlaceBetExecutor.cs
> +            //                                                              $"and state {stateService.GetCurrentState(message.User)}");
Давай пока раскомментируем, оставим как отладочную информацию

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/Executor/IExecutor.cs
> +    public interface IExecutor<T>: IExecutor //внутри экзекьютора получим стэйт
Коммент наверное можно снести?

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +        ICommandType GetCurrentCommandType(ITelegramUser user);
Можно для удобства сделать этот метод `TryGet` с вот такой сигнатурой:

`bool TryGetCurrentCommandType(ITelegramUser user, out ICommandType commandType)`

2021-05-24 10:04 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +        ICommandType GetCurrentCommandType(ITelegramUser user);
Тогда будет очевидно и не надо будет возвращать `NoCommandType`

2021-05-24 10:07 UTC, Gordory requested changes

2021-05-24 10:07 UTC, Gordory commented on TelegramBot/MessageHandling/CommandParser.cs
> +                var names = Attribute.GetCustomAttributes(type).OfType<AliasAttribute>().SelectMany(a => a.Aliases).ToList();
`ToList()` можно убрать

2021-05-25 08:59 UTC, lil-il commented on .gitignore
> +.TelegramBot/Config.json/
Почему не существует? у меня ж в ней весь проект

2021-05-25 09:03 UTC, lil-il commented on TelegramBot/BettingShop.TelegramBot.csproj
> +  </ItemGroup>
А я не знаю, оно само прописалось

2021-05-25 09:05 UTC, lil-il commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +                        break;
Будет, там ниже в "else" обрабатывается ситуация "Start"

2021-05-25 09:06 UTC, lil-il commented on TelegramBot/Executor/Executors/GetMyIdExecutor.cs
> +    public class GetMyIdExecutor: IExecutor
Блин, у меня локально его вообще нет, я не понимаю, откуда он здесь

2021-05-25 11:57 UTC, lil-il commented on TelegramBot/IUserCommandService.cs
> +        private static Dictionary<ITelegramUser, ICommandState> userState = new Dictionary<ITelegramUser, ICommandState>();
Потому что если делать не статиком, то он каждый раз пересоздается и стэйты не сохраняются

2021-05-25 12:29 UTC, lil-il commented on TelegramBot/Program.cs
> +                commandParser);
Я, видимо, не до конца понимаю как работает контейнер, но если я пишу вот так 
var telegramHandler = container.GetInstance<BotHandler>();
то у меня все валится

2021-05-25 12:36 UTC, lil-il commented on TelegramBot/IUserCommandService.cs
> +        ICommandType GetCurrentCommandType(ITelegramUser user);
А как тогда обрабатывать случай, когда не введена никакая команда?

2021-05-25 12:40 UTC, lil-il commented on TelegramBot/IUserCommandService.cs
> +        ICommandType GetCurrentCommandType(ITelegramUser user);
Насколько вообще плохо будет оставить, как сейчас есть?

2021-05-25 12:45 UTC, lil-il commented on TelegramBot/IUserCommandService.cs
> +        ICommandType GetCurrentCommandType(ITelegramUser user);
Я, наверное, просто не понимаю как с модификатором out работать, но мне как будто неочевидно удобство
Я сейчас попробовал так поменять и чет не очень понял, как это вызывать

2021-05-25 12:54 UTC, lil-il commented on TelegramBot/IUserCommandService.cs
> +        ICommandType GetCurrentCommandType(ITelegramUser user);
Короче, я как-то сделал, но не уверен, что ты это имел в виду

2021-05-25 13:52 UTC, Gordory commented on TelegramBot/BotHandler.cs
>                  if (commandType.Name == "NoCommand")
Теперь можно так сделать

```suggestion
                if (commandTypeService.TryGetCurrentCommandType(userRequest.User, out var commandType))
```

2021-05-25 13:52 UTC, Gordory commented on .gitignore
> +.TelegramBot/Config.json/
Точка осталась после изменений

2021-05-25 14:26 UTC, Gordory commented on TelegramBot/BotHandler.cs
>                  if (commandType.Name == "NoCommand")
Раз `NoCommand` больше нет

2021-05-25 14:26 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +                            "Введите возможные исходы вашего события");
У тебя дважды запрашиваются исходы события? Что-то тут не так

2021-05-25 14:26 UTC, Gordory commented on TelegramBot/UserCommandStateService.cs
> +                commandType = new NoCommandType();
Я предлагаю удалить класс `NoCommandType` и тут просто делать
```suggestion
                commandType = null;
```

2021-05-25 14:26 UTC, Gordory commented on TelegramBot/Executor/Executors/CreateEventExecutor.cs
> +            client = botClient;
И везде где еще осталось видимо

2021-05-25 14:36 UTC, Gordory requested changes

2021-05-25 14:36 UTC, Gordory commented on TelegramBot/FormingEvent.cs
> +        public string  Outcomes { get; set; }
В чем разница?

2021-05-25 14:36 UTC, Gordory commented on TelegramBot/Program.cs
>              var json = r.ReadToEnd();
Можно просто `File.ReadAllText()`

2021-05-25 14:36 UTC, Gordory commented on TelegramBot/Program.cs
> +            container.Register<UserCommandStateService, UserCommandStateService>();
А зачем класс на класс регистрировать?

2021-05-25 14:36 UTC, Gordory commented on TelegramBot/Program.cs
> +                commandParser);
Если ты уже зарегистрировал эти классы - зачем ты еще раз их тут создаешь?

2021-05-25 14:36 UTC, Gordory commented on TelegramBot/Program.cs
> +                commandParser);
Просто попроси контейнер создать тебе нужный класс

2021-05-25 14:36 UTC, Gordory commented on TelegramBot/UserCommandStateService.cs
> +            commandType = (ICommandType)Activator.CreateInstance(userState[user].GetType().GetInterfaces().Where(T=>T.IsGenericType).First().GetGenericArguments().First());
Если у тебя вдруг появится новый state, который будет наследовать какой-то другой generic интерфейс? Тут всё сломается, а ты не узнаешь почему.

Поэтому лучше сделать как я предлагал и выдернуть точно нужный интерфейс

2021-05-26 05:43 UTC, Gordory commented on TelegramBot/Program.cs
> +            container.Register<UserCommandStateService, UserCommandStateService>();
Можно просто `container.Register<SomeClass>();`

2021-05-26 09:45 UTC, Gordory commented on TelegramBot/IUserCommandService.cs
> +        private static Dictionary<ITelegramUser, ICommandState> userState = new Dictionary<ITelegramUser, ICommandState>();
Всё верно, но у тебя несколько экземпляров класса не должны обращаться к одинаковым полям. А регистрация синглтоном должна обеспечить единственный экземпляр на всю программу.

2021-05-26 09:51 UTC, Gordory commented on TelegramBot/Program.cs
> +            var r = new StreamReader("C:/Users/iprok/bot/betting_shop/TelegramBot/Config.json");
CopyAlways нету сейчас в твоей ветке, проверил

2021-05-26 10:31 UTC, Gordory commented on BettingShop.TelegramBot/BotHandler.cs
> +                        $"Called NoCommandExecutor with message {e.Message.Text}");
Я думаю тут что-то другое надо написать. Может вызвать лучше `HelpExecutor` тогда?

2021-05-26 10:31 UTC, Gordory commented on BettingShop.TelegramBot/Config.cs
> +    class Config
`public`

2021-05-26 10:31 UTC, Gordory commented on BettingShop.TelegramBot/MessageHandling/CommandParser.cs
> +                if (names.Contains(commandString))
Тут надо воткнуть `ToLowerInvariant()` и у Aliases и у commandString, чтобы большие-маленькие буквы не влияли

2021-05-26 10:31 UTC, Gordory commented on BettingShop.TelegramBot/UserCommandStateService.cs
> +                .GetGenericArguments().First());
Тут 2 варианта осталось, удали старый.

И разбей код на несколько переменных. Первая - это видимо получение нужного типа, вторая - это CreateInstance. А то читать больно

2021-05-26 10:31 UTC, Gordory commented on BettingShop.sln
> +Global
Кажется этот global надо снести, 1 строку

2021-05-26 10:31 UTC, Gordory commented on TelegramBot/Executor/Executors/HelpExecutor.cs
> +                $" - /profileinfo - посмотреть информацию о профиле");
Зарезолви, как прочитаешь

2021-05-26 10:31 UTC, Gordory commented on TelegramBot/BotHandler.cs
> +            var userRequest = parser.ParseMessage(e.Message.Text);
Зарезолви, как прочитаешь

2021-05-26 10:35 UTC, Gordory commented on TelegramBot/Program.cs
> +            telegramHandler.StopReceiving();
Накидал пример как это сделать в текущих реалиях
https://pastebin.com/AvhCWGmA

2021-05-28 08:57 UTC, Gordory approved these changes

2021-05-28 09:49 UTC, merged