Event api
lil-il/betting_shop pull request #5
Opened 2021-04-21 12:20 UTC by kseniabrsv

2021-04-21 14:45 UTC, Gordory commented on ExistingEventApi/Models/User.cs
> +}
Такс, мы вроде про модель Event-ов договаривались, что её опишем, все нужные поля

2021-04-21 14:48 UTC, Gordory commented
Давайте выкинем из ExistingEvent всю логику формирования id? 
Это должна быть просто модель, без логики.

И полностью сформируем все её поля

2021-04-21 15:20 UTC, kseniabrsv commented on ExistingEventApi/Models/User.cs
> +}
Я сейчас перезалила, потому что тогда изменения в файле почему-то не сохранились

> Такс, мы вроде про модель Event-ов договаривались, что её опишем, все нужные поля

2021-04-21 15:20 UTC, kseniabrsv commented on ExistingEventApi/Models/User.cs
> +}
> Такс, мы вроде про модель Event-ов договаривались, что её опишем, все нужные поля

А это я просто решила добавить модель пользователя плюсом

2021-04-21 15:22 UTC, kseniabrsv commented
> Давайте выкинем из ExistingEvent всю логику формирования id?
> Это должна быть просто модель, без логики.
> 
> И полностью сформируем все её поля

В отдельный класс создание ивента засунуть?

2021-04-21 15:31 UTC, Gordory reviewed
> В отдельный класс создание ивента засунуть?

Можно прямо в место, где ты конструктор вызываешь пока что. Давай тогда для простоты поменяем идентификатор на GUID и в месте где создаешь просто вызовешь Guid.NewGuid. Так мы пока что избавимся от головняка с дублированием айдишников

2021-04-21 15:31 UTC, Gordory commented on ExistingEventApi/Models/User.cs
> +        public List<ExistingEvent> EventsWithRates { get; set; }
Тут лучше использовать не явный `List`, а либо интерфейс `IList`, либо `ICollection`, чтобы не затачиваться на конкретный класс

2021-04-21 15:34 UTC, Gordory commented on ExistingEventApi/Models/User.cs
> +        public List<ExistingEvent> EventsWithRates { get; set; }
```suggestion
        public ICollection<ExistingEvent> EventsWithRates { get; set; }

```

2021-05-11 14:20 UTC, Gordory commented on ExistingEventApi/Models/ExistingEvent.cs
> +
Так, а исходы события задаются при создании? Как пользователь будет знать, на что конкретно ставить?

2021-05-11 14:20 UTC, Gordory commented on ExistingEventApi/Controllers/ExistingEventsController.cs
> +            return context.ExistingEvents.Any(e => e.Id.CompareTo(id) == 0);
Лучше использовать метод `Equals`, он попроще работает

2021-05-11 14:20 UTC, Gordory commented on ExistingEventApi/Controllers/ExistingEventsController.cs
> +            return context.ExistingEvents.Any(e => e.Id.CompareTo(id) == 0);
```suggestion
            return context.ExistingEvents.Any(e => e.Id.Equals(id));
```

2021-05-11 14:20 UTC, Gordory commented on ExistingEventApi/Models/User.cs
> +        public ICollection<ExistingEvent> EventsWithRates { get; set; }
А что значит `Rates` здесь?

2021-05-11 14:20 UTC, Gordory commented on ExistingEventApi/Models/ExistingEvent.cs
>          public ExistingEvent(string name)
Я думаю что и контроллер целиком надо убрать, он ты `name`-то всё равно можешь задать через сеттер

И у тебя как раз будет чистая "доменная" модель

2021-05-11 14:20 UTC, Gordory commented on ExistingEventApi/Controllers/ExistingEventsController.cs
> +        public async Task<ActionResult<ExistingEvent>> PostEvent([FromBody] string name)
Кажется был вопрос, как сюда все поля передать - можно просто `[FromBody] ExistingEvent event`

2021-05-16 07:56 UTC, Gordory requested changes

2021-05-16 07:56 UTC, Gordory commented on ApiClient/BetEventClient.cs
>          public BetEvent Create(BetEventMeta betEventMeta)
Давай все методы клиента сделаем асинхронными. Тут например будет `public async Task<BetEvent> CreateAsync(BetEventMeta betEventMeta)`

2021-05-16 07:58 UTC, Gordory commented on ApiClient/BetEventClient.cs
>          public BetEvent Create(BetEventMeta betEventMeta)
Проблема будет с `GetAll()` но там давай возвращать `Task<BetEvent[]>`

2021-05-17 05:50 UTC, Gordory requested changes

2021-05-17 05:50 UTC, Gordory commented on ApiClient/BetEventClient.cs
> +            return await deletedEvent;
Из-за того что ты ожидаешь deletedEvent после удаления - могут быть спецэффекты, что вернётся null например. Лучше сделать чтобы сам метод API в теле ответа возвращал удалённую запись. И не делать отдельный запрос в апи. А то выходит что на один запрос реально делается два, а это дорого

2021-05-17 05:50 UTC, Gordory commented on BettingShop.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "EchoBotForTest", "EchoBotForTest\EchoBotForTest\EchoBotForTest.csproj", "{B6856B46-9849-4FD0-9C38-2B2BB77477B4}"
Так, лучше чужие проекты, которые не касаются этого PR не прибирать, тут могут при мерже возникнуть неприятные конфликты, потому что Илья тоже его перенес

2021-05-17 05:50 UTC, Gordory commented on BettingShop.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ExistingEventApi", "ExistingEventApi\ExistingEventApi.csproj", "{54875E58-CCC6-457E-B26F-F0A4483EC769}"
Предлагаю переименовать проекты. 
`ApiClient` в `BettingShop.Api.Client`
`ApiClient.Tests` в `BettingShop.Api.Client.Tests`
`ExistingEventApi` в `BettingShop.Api`

Тогда в дальнейшем после мержа всех веток у вас будет красота в солюшне. Остальным я такой же контракт имён советую.

2021-05-17 05:50 UTC, Gordory commented on BettingShop.sln
> +Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ExistingEventApi", "ExistingEventApi\ExistingEventApi.csproj", "{54875E58-CCC6-457E-B26F-F0A4483EC769}"
И не забыть переименовать все namespace внутри этих проектов

2021-05-17 05:53 UTC, Gordory requested changes

2021-05-17 05:53 UTC, Gordory commented on ApiClient/IBetEventClient.cs
> +        Task<BetEvent> Create(BetEventMeta betEventMeta);
По общей договоренности между всеми разработчиками асинхронные методы должны иметь суффикс Async в имени. Тут должно получиться `CreateAsync`. Ну и везде стоит поправить и глянуть

2021-05-20 08:46 UTC, Gordory commented on ApiClient.Tests/UnitTest1.cs
> +        public async Task TestMethod1()
Название метода.

2021-05-20 08:46 UTC, Gordory commented on ExistingEventApi/Controllers/BetEventController.cs
> +        public async Task<ActionResult<IEnumerable<Client.Models.BetEvent>>> GetAllAsync()
Ой, я имел ввиду Async у методов клиента. Контроллер это исключение, тут можно добавлять а можно и нет

2021-05-20 09:49 UTC, Gordory approved these changes

2021-05-23 08:28 UTC, merged